---
title: "About"
---
Analysis of the Denver Health Paramedics call volumes from 2010 - 2018.  The available call volume data includes the total ammount of 911 ambulance calls over any given hour within the specified years. This data only includes 911 calls within the city and county of Denver.  The Denver Health Paramedics are also the primary ALS providers for the cities of Sheridan, Glendale, Englewood, and the Skyline Fire Protection District. For more information about the Denver Health Paramedic Division visit [denverhealthparamedics.org](www.denverhealthparamedics.org).

---

This is an extension of a collaborative project, created for additional analysis and coding examples.  Project details, including the data set used, can be viewed on [GitHub](https://github.com/ChrisELarson/DenverEMS).

The raw files for this website can also be viewed on [GitHub](https://github.com/ChrisELarson/DenverEMS_rmd).

---

Data analysis and modeling using [R statistical software](https://www.r-project.org).

---

Planned further development:

- Continued Volume Analysis
- Predictive model used
- Time series analysis