---
title: "About"
---
Analysis of the Denver Health Paramedics call volumes from 2010 - 2018.  The available call volume data includes the total ammount of 911 ambulance calls over any given hour within the specified years. This data only includes 911 calls within the city and county of Denver.  The Denver Health Paramedics are also the primary ALS providers for the cities of Sheridan, Glendale, Englewood, and the Skyline Fire Protection District. For more information about the Denver Health Paramedic Division visit [denverhealthparamedics.org](www.denverhealthparamedics.org).

Predictive modeling using weather data and home games for professional sports teams to see if these events have any predictive power in determing the number of EMS calls. The weather factors examined were temperature and precipitation.  Temperature for each hour period was determined by rounding temperature values to the nearest hour and taking the mean value over the hour.  Precipitation determined as a yes or no value, yes if there was any precipitation over the hour, no otherwise.

***

Data analysis and modeling using [R statistical software](https://www.r-project.org) with the R libraries tidyverse, ggplot2, and plotly

***

This website is intended as a more visually appealing way to show some of the analysis performed for this project.  Supplemental information including more coding used, the power point for presentation, and the final data set constucted can be found on GitHub [here](https://github.com/ChrisELarson/DenverEMS).  

## **SITE UNDER CONSTRUCTION**